import pandas as pd

country_mapping = {
    'Afghanistan': 'Islamic Republic of Afghanistan',
    'Algeria': "People's Democratic Republic of Algeria",
    'Angola': 'Republic of Angola',
    'Argentina': 'Argentine Republic',
    'Australia': 'Commonwealth of Australia',
    'Armenia': 'Republic of Armenia',
    'Azerbaijan': 'Republic of Azerbaijan',
    'Bangladesh': "People's Republic of Bangladesh",
    'Bahamas': 'Commonwealth of The Bahamas',
    'Bahrain': 'Kingdom of Bahrain',
    'Belarus': 'Republic of Belarus',
    'Belgium': 'Kingdom of Belgium',
    'Bhutan': 'Kingdom of Bhutan',
    'Bolivia': 'Plurinational State of Bolivia',
    'Brazil': 'Federative Republic of Brazil',
    'Bulgaria': 'Republic of Bulgaria',
    'Canada': 'Canada',
    'Cambodia': 'Kingdom of Cambodia',
    'Chad': 'Republic of Chad',
    'Chile': 'Republic of Chile',
    'China': "People's Republic of China",
    'Colombia': 'Republic of Colombia',
    'Croatia': 'Republic of Croatia',
    'Costa Rica': 'Republic of Costa Rica',
    'Cuba': 'Republic of Cuba',
    'Czech Republic': 'Czech Republic',
    'Democratic People\'s Republic of Korea': 'Democratic People\'s Republic of Korea (North Korea)',
    'Democratic Republic of the Congo': 'Democratic Republic of the Congo',
    'Denmark': 'Kingdom of Denmark',
    'Dominican Republic': 'Dominican Republic',
    'Ecuador': 'Republic of Ecuador',
    'El Salvador': 'Republic of El Salvador',
    'Egypt': 'Arab Republic of Egypt',
    'Estonia': 'Republic of Estonia',
    'Ethiopia': 'Federal Democratic Republic of Ethiopia',
    'Finland': 'Republic of Finland',
    'France': 'French Republic',
    'Gambia': 'Republic of The Gambia',
    'Georgia': 'Georgia',
    'Germany': 'Federal Republic of Germany',
    'Ghana': 'Republic of Ghana',
    'Greece': 'Hellenic Republic',
    'Haiti': 'Republic of Haiti',
    'Hungary': 'Hungary',
    'Iceland': 'Republic of Iceland',
    'India': 'Republic of India',
    'Indonesia': 'Republic of Indonesia',
    'Iran': 'Islamic Republic of Iran',
    'Iraq': 'Republic of Iraq',
    'Ireland': 'Ireland',
    'Israel': 'State of Israel',
    'Italy': 'Italian Republic',
    'Jamaica': 'Jamaica',
    'Japan': 'Japan',
    'Jordan': 'Hashemite Kingdom of Jordan',
    'Kazakhstan': 'Republic of Kazakhstan',
    'Kenya': 'Republic of Kenya',
    'Kuwait': 'State of Kuwait',
    'Kyrgyzstan': 'Kyrgyz Republic',
    'Latvia': 'Republic of Latvia',
    'Lebanon': 'Lebanese Republic',
    'Liberia': 'Republic of Liberia',
    'Libya': 'State of Libya',
    'Lithuania': 'Republic of Lithuania',
    'Luxembourg': 'Grand Duchy of Luxembourg',
    'Madagascar': 'Republic of Madagascar',
    'Malaysia': 'Malaysia',
    'Maldives': 'Republic of Maldives',
    'Malta': 'Republic of Malta',
    'Mexico': 'United Mexican States',
    'Monaco': 'Principality of Monaco',
    'Mongolia': 'Mongolia',
    'Myanmar': 'Republic of the Union of Myanmar',
    'Namibia': 'Republic of Namibia',
    'Nepal': 'Federal Democratic Republic of Nepal',
    'Netherlands': 'Kingdom of the Netherlands',
    'Niger': 'Republic of Niger',
    'Nigeria': 'Federal Republic of Nigeria',
    'New Zealand': 'New Zealand',
    'North Macedonia': 'Republic of North Macedonia',
    'Norway': 'Kingdom of Norway',
    'Oman': 'Sultanate of Oman',
    'Pakistan': 'Islamic Republic of Pakistan',
    'Panama': 'Republic of Panama',
    'Paraguay': 'Republic of Paraguay',
    'Peru': 'Republic of Peru',
    'Philippines': 'Republic of the Philippines',
    'Poland': 'Republic of Poland',
    'Portugal': 'Portuguese Republic',
    'Qatar': 'State of Qatar',
    'Republic of Korea': 'Republic of Korea (South Korea)',
    'Romania': 'Romania',
    'Russian Federation': 'Russian Federation',
    'Saudi Arabia': 'Kingdom of Saudi Arabia',
    'Senegal': 'Republic of Senegal',
    'Seychelles': 'Republic of Seychelles',
    'Slovakia': 'Slovak Republic',
    'Slovenia': 'Republic of Slovenia',
    'Somalia': 'Federal Republic of Somalia',
    'Singapore': 'Republic of Singapore',
    'South Africa': 'Republic of South Africa',
    'South Sudan': 'Republic of South Sudan',
    'Spain': 'Kingdom of Spain',
    'Sudan': 'Republic of the Sudan',
    'Switzerland': 'Swiss Confederation',
    'Syrian Arab Republic': 'Syrian Arab Republic',
    'Thailand': 'Kingdom of Thailand',
    'Turkey': 'Republic of Turkey',
    'Uganda': 'Republic of Uganda',
    'Ukraine': 'Ukraine',
    'Uruguay': 'Oriental Republic of Uruguay',
    'United Arab Emirates': 'United Arab Emirates',
    'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom of Great Britain and Northern Ireland',
    'United States of America': 'United States of America',
    'Venezuela': 'Bolivarian Republic of Venezuela',
    'Vietnam': 'Socialist Republic of Vietnam',
    'Yemen': 'Republic of Yemen',
    'Zimbabwe': 'Republic of Zimbabwe'
}

file_path = r'C:\Users\Mihir\Desktop\Matrices .xlsx'
sheet_name = 'UNODC - CND'
df = pd.read_excel(file_path, sheet_name=sheet_name)

df['Allocation'] = df['Allocation'].replace(country_mapping)

df.to_excel(file_path, sheet_name=sheet_name, index=False)
